modLoader="javafml"
loaderVersion="[31,)"
license="Public Domain"
issueTrackerURL="https://github.com/Phylogeny/JEIEnchantmentInfo/issues"
[[mods]]
    modId="jeienchantmentinfo"
    version="${file.jarVersion}"
    displayName="JEI Enchantment Info"
    description="This mod adds JEI info entries for enchantments. Press R while hovering over a book with a single enchantment to view info about it."
    displayURL="https://www.curseforge.com/minecraft/mc-mods/jei-enchantment-info"
    updateJSONURL="https://github.com/Phylogeny/JEIEnchantmentInfo/raw/1.16.1/update.json"
    credits="Descriptions for vanilla enchantments are from the 'Enchanting' page of the Official Minecraft Wiki: https://minecraft.gamepedia.com/Enchanting#Summary_of_enchantments"
    authors="Phylogeny"
    logoFile="logo.png"
[[dependencies.jeienchantmentinfo]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.jeienchantmentinfo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.jeienchantmentinfo]]
    modId="jei"
    mandatory=true
    versionRange="[6,)"
    ordering="AFTER"
    side="CLIENT"